### ISSUE TITLE
Fabrica de valores falsos para formularios

### ISSUE THREAD

**Issue by marioidival** [braziljs/ideias#1]
Bom, quem trabalha não apenas com websites, mas também com sistemas web - em desenvolvimento - normalmente fazemos alguns testes diretamente com formulários, e se tivermos um formulário grande, é complicado de preencher todos, toda vez. 

Eu sei que isso poderia ser resolvido com testes, mas sabemos que muitas pessoas ainda não usam testes com deveriam, por isso essa ideia. Ter um script que gere valores falsos para formulários web, em ambiente de desenvolvimento.

é isso. :)

**Comment by netojose** [comment]
para gerar dados falsos, eu uso essa ferramenta:

http://www.generatedata.com/

Ela possui algumas limitações quando rodando no endereço acima, mas pode ser baixada e roda localmente em um servidor que rode php.

Ela pode gerar dados em SQL, JSON, HTML, XML, CSV, etc.
É interessante porque você pode gerar diversos tipos de dados (listas, incrementais, nomes, telefone, emails, etc.)

Eu sei que isso não responde diretamente ao problema proposto, mas se precisar de algo que já popule o banco, para fazer testes em listagens por exemplo, é uma boa.

E também serve como referência para o projeto que foi aqui proposto

**Comment by zenorocha** [comment]
Fala @marioidival,

Existem uma série de soluções para isso, uma simples pesquisa no Google por `form filler` e você consegue encontrar coisas como:
- http://www.phpied.com/form-auto-fill-bookmarklet/
- https://github.com/dsheiko/autofill
- http://www.benjaminkeen.com/open-source-projects/smaller-projects/form-filler-bookmarklet/
- http://en.wikipedia.org/wiki/Selenium_%28software%29
- https://chrome.google.com/webstore/detail/form-filler/bnjjngeaknajbdcgpfkgnonkmififhfo?hl=en
- http://www.roboform.com/form-filler
- https://www.dashlane.com/autofill

O que iria diferenciar disso?

**Comment by bernardodiasc** [comment]
https://www.npmjs.com/package/selenium-webdriver :)

**Comment by felquis** [comment]
Iria fazer a mesma coisa que o Zeno fez acima, já existe muitas soluções para isso.

Daria o tópico como encerrado.
