### ISSUE TITLE
Mais visibilidade ao projeto Cerebro

### ISSUE THREAD

**Issue by zenorocha** [braziljs/ideias#10]
Uma iniciante incrível que surgiu alguns meses atrás é o projeto [Cerebro](http://cerebrobr.github.io/cerebro/) que busca agregar conteúdo na língua portuguesa em diversas verticais.

Como será que a @braziljs podia ajudar?

/cc @vitorbritto @hugobessaa @IAMFELIPESOUZA @nicholasess @pedropolisenso @thulioph

**Comment by nicholasess** [comment]
Muito obrigado pelo contato Zeno.
Acredito que a visibilidade do projeto é interessante, pois ela é restrita aos nossos amigos e pessoas que seguem a página no facebook.
Se de alguma forma pudessem expor os repositorios do cérebro a cada semana, ou até mesmo criarmos um post a respeito e a BrazilJs publicar. Acho que seria uma boa.
Esse é meu ponto de vista

**Comment by zenorocha** [comment]
Exatamente! Adorei tua proposta de um post a respeito disso no site da BrazilJS, acho que é um bom passo inicial antes de amadurecermos uma forma melhor de expor aquilo.

@nicholasess topa elaborar esse texto e enviar um pull request no repositório [braziljs/braziljs.org](https://github.com/braziljs/braziljs.org)?

**Comment by nicholasess** [comment]
O post precisa estar em um blog ou é apenas textos em um arquivo README.md?
Não entendi muito bem a sugestão.
@zenorocha

**Comment by zenorocha** [comment]
A sugestão é escrever um texto apresentando o projeto no blog. Aqui vai um exemplo de blogpost publicado: http://braziljs.org/blog/braziljs-conf-2013-teaser-e-douglas-crockford/

Para mandar é só fazer um pull request com um arquivo markdown, como em: https://github.com/braziljs/braziljs.org/tree/master/src/documents/blog

Ficou mais claro?

**Comment by nicholasess** [comment]
Muito mais simples do que imaginei.
Obrigado @zenorocha

**Comment by hugooliveirad** [comment]
@zenorocha ótima ideia para nos ajudar a dar mais visibilidade para o Cerebro. É ótimo saber dessa intenção. Uma página com projetos brasileiros interessantes seria muito bom também. O que acha?

@nicholasess se quiser ideias/ajuda para o post, pode contar comigo.

**Comment by nicholasess** [comment]
@hugobessaa sem dúvidas, toda ajuda é bem vinda.
Estou pensando em falar de um contexto geral e depois apontar, qual é valor que cada repositório quer levar as pessoas.

**Comment by thulioph** [comment]
@nicholasess precisando de ajuda no post também pode contar comigo, não sei se seria legal após você iniciar a gente ir acompanhando.  Um post atrativo que diga o que é o cérebro, pra que serve e que todo mundo pode colaborar já dá pra chamar atenção, uma rápida explanação sobre os repositórios internos seria legal também :)

**Comment by nicholasess** [comment]
Fecho, valeu a todos

**Comment by pedropolisenso** [comment]
Olá pessoal, bom dia. @zenorocha agradecemos por acreditar na ideia do Cerebro e tentar de alguma forma ajudar a galera da comunidade. @nicholasess e @hugobessaa o que vocês precisarem, podem contar comigo, ficarei muito feliz em ajudá-los.

**Comment by vitorbritto** [comment]
Bom dia senhores! Fico muito feliz em saber que temos o mesmo pensamento para com o crescimento da comunidade e fazê-la crescer com iniciativas brasucas.

Obrigado pelo convite @zenorocha! 

Acredito que temos algo bacana na apresentação da própria organização. De qualquer forma, posso criar um _gist_ ou publicar uma ideia/reformulação aqui mesmo, para que todos opinem e deixem suas sugestões/considerações. O que acham?

Além disso, para este ano, existem algumas ideias para que o CEREBRO consiga uma maior visibilidade e consiga ajudar mais pessoas. Algumas seriam: 
- **Weekly** destacando novidades na organização e projetos _open source_.
- **Podcast** com um formato FAQ, onde teríamos a duração de 10 minutos (no máximo), respondendo 2 perguntas por episódio sobre temas de tecnologia e comunicação. Neste Podcast, gostaria de dar espaço a quem está começando também. Jovens talentos que se prontifiquem a responder uma das dúvidas. Aqueles carinhas que estão escondidos, mas entendem muito bem do assunto. A ideia é mostrar que todos tem espaço e podem crescer **com a comunidade**. 

Toda sugestão é muito bem vinda. :neckbeard: 

_Summon:_ @nicholasess @hugobessaa @thulioph @pedropolisenso

**Comment by iamfelipemattos** [comment]
show de bola hein @vitorbritto, apoio essa causa!

**Comment by hugooliveirad** [comment]
Ótimo @vitorbritto. Um hangouts pode ser uma boa também.

**Comment by pedropolisenso** [comment]
Boa @vitorbritto mandou bem com os planos pra 2015. Vejo isso como um amadurecimento muito produtivo pra organização. A ideia do @hugobessaa é ótima tbm, a fim de propor uma organização para ajustar as ideias.

**Comment by thulioph** [comment]
Gostei das ideias @vitorbritto. Uma coisa que sinto falta é o [Devcast,](https://github.com/DevCastBrasil/) tinha aquele "compromisso" de data, aprendi muito assistindo os vídeos e com essas propostas muita gente também vai aprender.

Assim como o @hugobessaa falou, hangouts seria muito legal também, convidar "Aqueles carinhas que estão escondidos" pra apresentar algum conteúdo seria irado!

**Comment by nicholasess** [comment]
@vitorbritto estou começando a escrever o que poderia ser ideial no meu ponto de vista, ai cada um faz o mesmo e juntamos tudo pra ficar bom o texto.

**Comment by zenorocha** [comment]
Acho que estamos convergindo cada vez mais @vitorbritto. Seria legal saber dos planos de reformulação de vocês, assim ao invés de criarmos coisas novas com relação à conteúdo, nós podemos só linkar para o que vocês já estão fazendo.

Sobre o plano da weekly, por que não contribuir com a [BrazilJS Weekly](http://us5.campaign-archive.com/?u=77b6594f10bba05dcc722c80e&id=2f88a7522d)? Já foram mais de 90 edições e são mais de 3.000 subscribers. Podemos aproveitar esse público para potencializar o impacto dos links.

Um podcast novo seria extremamente legal de ver, super apoio e podemos inclusive listar na home como fizemos com o Codetalks (https://github.com/braziljs/braziljs.org/pull/154).

**Comment by vitorbritto** [comment]
Sem dúvidas @zenorocha. Não preparei um planejamento para os novos planos. As ideias estão muito frescas ainda. De qualquer forma, assim que tiver algo mais sólido do que passei anteriormente, vou compartilhar com todos. Sugestões são muito bem vindas também.

A ideia do Weekly é para somar à outras Weeklys brasucas, assim como a da BrazilJS. Não somente, destacar o que temos de novo na organização CEREBRO. Sem dúvidas, podemos unir forças para crescer juntos e ajudar a comunidade. 

Quanto ao podcast, estou bem animado para que ganhe vida logo.  Acredito que o formato ficará bem interessante e vai ajudar bastante a comunidade.

Obrigado à todos! =]

_Summon:_ @nicholasess @hugobessaa @thulioph @pedropolisenso @IAMFELIPESOUZA

**Comment by vitorbritto** [comment]
@nicholasess Show de bola! Vou formatar algo no horário do almoço e deixo registrado aqui para vocês avaliarem. Combinado?

_Summon:_ @zenorocha @hugobessaa @thulioph @pedropolisenso @IAMFELIPESOUZA

**Comment by pedropolisenso** [comment]
Perfeito. Fico no aguardo
Em 23/01/2015 11:25, "Vitor Britto" notifications@github.com escreveu:

**Comment by hugooliveirad** [comment]
Sensacional. Esperando o que você escreveu, @vitorbritto.

**Comment by iamfelipemattos** [comment]
maravilha, também estou no aguardo da análise.

**Comment by vitorbritto** [comment]
Pessoal, segue um breve descritivo para publicar no BrazilJS. Aguardo sugestões e considerações dos senhores.

---

Acreditamos que você saiba da importância em dominar o idioma inglês na área de Desenvolvimento, Programação e afins. Porém, sabemos também que nem todos possuem meios para ingressar em um curso de inglês. É verdade que dispomos de cursos online gratuitos, mas a presença de um professor e o _networking_ com os colegas em sala de aula é de grande ajuda. Nem todo mundo é autodidata ou nasce num berço de ouro. Não é verdade?

Sendo assim, foi criado o CEREBRO. Um espaço que vai reunir muito conteúdo interessante em português e ser o _help_ inicial nos seus estudos até que você fique fera no inglês.

O CEREBRO possui uma organização no GitHub com diversos repositórios. Um espaço útil e colaborativo. Além disso, está também no Facebook, onde é possível acompanhar as novidades da organização. 

Toda contribuição é muito bem vinda, seja dando sugestões ou adicionando novos materiais. Ajude no fortalecimento da comunidade brasileira com conteúdo de qualidade. Contamos com a sua participação!

CEREBRO no GitHub: https://github.com/cerebrobr
CEREBRO no Facebook: https://www.facebook.com/cerebroproject

Visite o nosso site para mais informações: http://cerebrobr.github.io/cerebro/

---

_Summon:_ @zenorocha @nicholasess @hugobessaa @thulioph @pedropolisenso @IAMFELIPESOUZA

**Comment by nicholasess** [comment]
Segue minha parte.

O cérebro nasceu de uma proposta de agregar conteúdos para desenvolvedores web, tanto em português quanto inglês.
Português, pois é a lingua nativa e para alcançar o publico que esta iniciando, nada mais justo que isso. E em inglês, pois é a lingua oficial, a maioria dos conteúdos estão em inglês e força os desenvolvedores a correrem atrás e se atualiza diante dos desafios.

No inicio eram três pessoas, hoje são centenas de pessoas colaborando, o time é composto por 3 níveis:
Owners: São responsáveis em manter a ordem na casa, mas todos do cerebrobr liberdade de expor a opinião e colaborar com mudanças.
Editores: São responsáveis avaliam os PRs e fazem o merge para os repositórios.
Colaboradores: São responsáveis adicionar novos conteúdos e atualizar conteúdos quebrados e etc.

Além da equipe o cérebro contém diversos repositórios, cada um com um propósito diferente.

O mais popular, com 171 stars é o Biblioteca. Esse repositório tem como princípio conter conteúdos em geral, mas apenas conteudo em ingles, por exemplo: Frameworks, e-commerce, deploy e etc.
Para encontrar conteúdo em português, o repositório correto se chama Artigos, nele você irá encontrar diversos conteúdos interessantes.
Existem outros repositórios como:

Slides: Slides de palestras e meetups apresentados em eventos de tecnologia no Brasil

Apresentações: Repositório com palestras brasileiras de Desenvolvimento, Design e Marketing Digital 

Meetups: Lista os meetups feitos pela comunidade dev do Brasil.

Cursos: Lista cursos que vão acontecer ou até mesmo os videos disponibilizados gratuitamente.

Adesivos: Uma coleção de adesivos para desenvolvedores. 

Comunidades: Repositório com lista para grupos, organizações e comunidades online. 

Documentações: Documentações em português.

Universidade: Lista com a grade do respectivo curso de graduação com conteúdos da internet. 

Glossário: Lista com termos técnicos utilizados na Ciência da Computação, Programação e afins. 

E muito mais !

**Comment by pedropolisenso** [comment]
[SUGESTÕES]

Fala pessoal, eu achei o texto do @vitorbritto e do @nicholasess muito bom, estão bem explicados e bem objetivo falando da proposta da  organização. Porém a proposta do @vitorbritto é bem mais resumida. Podemos tentar unir os 2 textos e ver no que dá. A lista de repositórios contendo a explicação ao lado que o @nicholasess propôs é bem interessante também, porém como são muitos repositórios seria legal listar os que poderia, inicialmente, ajudar a galera como: Cursos, Artigos, Bibliotecas e etc.

Eu analisei os links passados do CEREBRO e vi que tem repositórios ainda sem conteúdo e outros com poucos conteúdo como: Cursos, Universidade, Glossário, Guias e etc. Podemos incentivar o pessoal a vir contribuir na organização e alimentar os repositórios com conteúdo de todo o Brasil, assim como o repositório de Meetups. 

No site achei as informações bem distribuídas e bem informativa, podemos inserir um "Menu" apontando para o repositório de Meetups e criar uma "Section" de PodCast. 

Enfim creio eu que vai dar certo essa iniciativa e as ideias apresentadas, fico muito feliz em poder contribuir.

**Comment by nicholasess** [comment]
@pedropolisenso pode criar uma issue no repositório cerebro para intensificarmos nossas forças nos repositórios que não tem tantos conteúdos?
 Lista todos os repositórios que estão nessa situação, obrigado

**Comment by pedropolisenso** [comment]
Claro @nicholasess sem problemas algum, assim que chegar a casa, farei isso. :+1:

**Comment by thulioph** [comment]
Assim como o @pedropolisenso falou, unir os dois textos de @nicholasess e do @vitorbritto dá um mix legal e um panorama geral. Acho a ideia de levar pro universo dos X-Men legal, já que a logo e o nome faz referência, tentei cria um texto convidativo mostrando o "poder" do Cerebro, explanar o que ele tem e fazer a referência pro da Marvel.

Cc: @zenorocha @nicholasess @hugobessaa @vitorbritto  @pedropolisenso @IAMFELIPESOUZA

---

Já ouviu falar do **Cerebro**? Possa ser que você conheça o dos _X-Men_, mas no momento estamos falando da organização criada para reunir muito conteúdo interessante e ser o help nos seus estudos.

Assim como o dos X-Men, o **Cerebro** aumenta os seus poderes na medida que você vai colaborando com novos conteúdos para ele e o melhor disso tudo é que o conteúdo é todo em português, assim você vai ficando fera no inglês e vai ajudando muitas pessoas que estão começando assim como você um dia.

A organização é dividida em alguns repositórios específicos, afinal você não quer perder tempo procurando o conteúdo né? Você encontra desde artigos, adesivos, livros, cursos, ferramentas, guias, apresentações, meetups, podcasts, traduções, enfim, um grande acervo de conteúdo que foi criado **pela comunidade para a comunidade**. Quer conhecer mais sobre o projeto, colaborar ou até mesmo propor novos conteúdos? Acesse o [site](http://cerebrobr.github.io/cerebro/) ou através da página do [Facebook](https://www.facebook.com/cerebroproject) e entre para o nosso universo! :muscle:

**Comment by pedropolisenso** [comment]
Galera, ainda não tive tempo de Abrir as novas ISSUE em nossos repositório, mas hoje ainda eu farei isso ok? Agora precisamos correr com o planejado, certo? Já temos muito conteúdo que temos que dar um merge e transformar em um só. Vamos definir o texto para colocar la no Braziljs. Não vamos deixar cair no esquecimento ein. Abraços!

**Comment by nicholasess** [comment]
@pedropolisenso  eu não esqueci, achei o texto do @thulioph bem irado.
Aceito ele como o texto para ir ao braziljs, e vocês?
@hugobessaa @vitorbritto  @IAMFELIPESOUZA

**Comment by pedropolisenso** [comment]
Eu Gostei muito do texto do @thulioph também, está meio que descolado, como se tivesse falando diretamente pra pessoa, frente a frente. Por outro lado acho que deveria ter o link da organização do github para a galera ver os projetos que tem, um tipo de "conheça os repositório **aqui**". Minha opinião seria a seguinte...

Eu usaria o texto do @thulioph como apresentação, a listagem dos PRINCIPAIS repositórios que o @nicholasess sugeriu no texto dele e a organização de links do @vitorbritto Assim fica claro tudo que queremos passar: O texto sobre as informações da organização, os links organizados e a listagem de repositórios mais importantes, que na minha opinião seria: meetups / artigos / cursos / slides / comunidade /  biblioteca / universidade / ferramentas

Agora é esperar o restante ver o que seria legal.

**Comment by zenorocha** [comment]
Acho que pra discussão ficar mais objetiva, o ideal é criar um PR no [braziljs/braziljs.org](https://github.com/braziljs/braziljs.org). Assim vocês conseguem revisar linha por linha de uma forma bem melhor.

**Comment by nicholasess** [comment]
Galera, criei aqui o PR com o texto para definirmos o que precisa ser melhorado.
Segue o link do [arquivo](https://github.com/nicholasess/braziljs.org/blob/master/src/documents/blog/cerebrobr.md)

@vitorbritto @IAMFELIPESOUZA @pedropolisenso @hugobessaa

**Comment by pedropolisenso** [comment]
@nicholasess Li o arquivo e está muito bom, agradeço por seguir minha sugestão. O título acho que poderia ser bem curioso pra prender a galera sei lá, algo como: **Cerebro. Tenha tudo que precisa** / **Um repositório para suas necessidades** / **O Cerebro só quer ajudar você** / **Deus no céu e Cerebro na Terra** / **Você não precisa do Google para isso** / **Quer aprender? O Cerebro te ajuda**

Enfim, galera essas são mais algumas sugestões ok? pensei aqui bem rapidinho e dei pelo menos alguma ideia do que, de repente, poderia ser legal.

O que acham: @zenorocha @vitorbritto @hugobessaa @thulioph

**Comment by zenorocha** [comment]
Acho que podemos mover a discussão do texto para o PR e focar aqui em outras formas da BrazilJS impulsionar o Cerebro.

**Comment by pedropolisenso** [comment]
Beleza @zenorocha entendido. Então @nicholasess dá o PR e então veremos por la mesmo!

**Comment by nicholasess** [comment]
@hugobessaa @vitorbritto @pedropolisenso @IAMFELIPESOUZA 
segue o [PR](https://github.com/braziljs/braziljs.org/pull/170)

**Comment by thulioph** [comment]
Belezal, vou acompanhar de lá :*
