### ISSUE TITLE
Mais visibilidade para projetos regulares em vídeo

### ISSUE THREAD

**Issue by zenorocha** [braziljs/ideias#12]
Hoje existem algumas iniciativas bem legais em vídeo como o [DevCast](https://www.youtube.com/user/DevCastVideos) e o [Update Sem Where](https://www.youtube.com/channel/UCZmp5CT7ASVdDkRZMzptLFw).

Nós já costumamos divulgar na Weekly e redes sociais, mas como será que podemos dar mais visibilidade para esses projetos com a BrazilJS?

/cc @felquis @guisouza

**Comment by brunoborgesruiz** [comment]
Existem iniciativas, que não são em vídeo, que já são extremamente populares e que poderiam ter um a extensão em vídeo com um acoplamento claro. Por exemplo: http://loopinfinito.com.br/ é referencia em artigos de alta qualidade sobre front-end..... se estendermos para uma plataforma de vídeos da mesma qualidade....

**Comment by zenorocha** [comment]
Com certeza existem dezenas de iniciativas que não são em vídeo e que são extremamente populares. Artigos do @loopinfinito e @tableless já são comumente divulgados através da Weekly.

A ideia com essa issue não é criar uma plataforma de vídeos, isso seria um passo muito grande, mas sim criar um espaço para destacar canais de vídeo.

**Comment by rands0n** [comment]
Eu tenho vontade de criar um programa(canal) de desenvolvimento no YouTube. Parecido com canais como Galo Frito, Jovem Nerd, etc...

Pra mim uma iniciativa como essa seria algo maravilhoso. Penso em algo totalmente técnico ajudando o público de desenvolvedores a aprenderem novas tecnologias. O programa poderia conter entrevistas, material para estudo, tutoriais e sem contar que seria um local de descoberta de talentos e divulgação de projetos ;)

Um que chegou perto disso foi o DevCast. Gostei muito da iniciativa.

**Comment by brunoborgesruiz** [comment]
@zenorocha um lugar pra destacar os vídeos é uma boa. Mas talvez possamos criar uma canal que possa ser um dos geradores de conteúdo para este lugar de destaque de vídeos. Assim garantimos um periodocidade - no sentido de caso não tenhamos conteúdo para destacar possamos ja ter alguns produzidos para destacar. O que acham @zenorocha  e @randsonjs ?

**Comment by andersoonweb** [comment]
Ah algum tempo atrás estava pensando em fazer um Weekly sobre materiais front-end tipo o o conteúdo desses caras [aqui](https://www.youtube.com/user/gotreehouse/featured).Quando fui ver a fundo é bem trabalhoso, mas ainda não desistir da ideia, quem sabe num futuro próximo!

**Comment by felipenmoura** [comment]
eu tenho pensado em investir em vídeos...comprei uma câmera bacana e um tripe profissional.
so não sei ainda qual a dinâmica para adotarmos neste formato.
pensei algo como um mix de video aula com screen cast, e apresentação ou entrevista, filmando pessoas.
Dava pra fazer algo como responder perguntas, ou mostrar algumas novidades.
O que achariam disso? Seria como uma weekly, em video.

**Comment by zenorocha** [comment]
> Seria como uma weekly, em video.

;)
