### ISSUE TITLE
Guiando iniciantes para as referências certas

### ISSUE THREAD

**Issue by zenorocha** [braziljs/ideias#4]
Hoje em dia existem milhões de frameworks e buzzwords que confundem quem tá começando.

Por isso, muita gente pergunta como deve começar com JavaScript, quais os melhores livros, quais os melhores blogs, enfim qual o melhor caminho **em português**?

Geralmente eu indico links como:
- http://tableless.github.io/iniciantes
- http://www.luiztiago.com/post/34760239764/quero-aprender-ou-conhecer-melhor-javascript-por

Como podemos ajudar as pessoas a seguir um fluxo legal? Quais outros links vocês costumam indicar?

**Comment by cassiocardoso** [comment]
Pra quem quer aprender JS botando a mão na massa eu recomendo o Codecademy:

http://www.codecademy.com/en/tracks/javascript

**Comment by evansantos** [comment]
Eu costumo indicar estes abaixo...
- https://www.codeschool.com/paths/ (embora os cursos depois do level 1 sejam pagos)
- http://teamtreehouse.com/library/ (pago)
- e o codeacademy citado pelo @cassiocardoso

Embora existam muita coisas gratuita e de qualidade

**Comment by ghost** [comment]
Recomendo a galera descobrir novos métodos de aprendizagem e técnicas diferentes, situações.. Estou criando alguns posts explicando como estou aprendendo javascript via DevTools do Chorme. 

alguns links diários
http://www.w3schools.com/ (para tirar dúvidas no trabalho)
http://uptodate.frontendrescue.org/pt/ (ótima referência para se manter atualizado no mundo front)
e codeacademy @cassiocardoso (muito bom)

livros que já li
http://www.saraiva.com.br/use-a-cabeca-javascript-2611562.html (boa didática)
http://novatec.com.br/livros/aprendendojavascript/ (vai do inicio ao intermediário da linguagem)

**Comment by erickpatrick** [comment]
Eu [traduzo artigos para o Tuts+](http://tutsplus.com/authors/erick-patrick) e já traduzi aproximadamente 30 artigos sobre JavaScript para lá. Nem todos são para iniciantes, contudo, acredito que são bons materiais de estudo. Só seguir [este link para os artigos sobre JavaScript](https://github.com/erickpatrick/tutsplus#javascript)

**Comment by fczuardi** [comment]
muito bom @erickpatrick ! Você já pensou em traduzir páginas e artigos da MDN? https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize/Translating_pages

**Comment by rands0n** [comment]
Em relação a traduções, tem também o [Eloquent Javascript](http://eloquentjavascript.com.br). É um ótimo livro de JavaScript. Se fizessemos um esforço para terminar a tradução dele já teriamos um ótimo conteúdo para iniciantes.

Além do livro tem exercicios práticos, assim a pessoa aprende e ainda prática ;)

**Comment by erickpatrick** [comment]
@fczuardi da MDN ainda não, mas vez ou outra traduzo do Unity, do PHP e do WordPress. Uma hora vou arranjar um tempo para a MDN também ;)

**Comment by joaostein** [comment]
O @ericdouglas tem um repo que pode ser um bom ponto de partida para agregar tradução de artigos https://github.com/ericdouglas/traduz-ai e usado como referência para iniciantes e pessoas que buscam conhecimento intermediário e avançado.

**Comment by zenorocha** [comment]
Curti demais esse projeto do @ericdouglas, podíamos ter uma página dedicada a traduções no site braziljs.org baseado naquele repositório.

**Comment by ericdouglas** [comment]
@zenorocha +1 seria muito massa!

**Comment by zenorocha** [comment]
@ericdouglas, pode propor essa ideia numa issue separada?

**Comment by ericdouglas** [comment]
Sim @zenorocha !

**Comment by ericdouglas** [comment]
@zenorocha done! #9

**Comment by evansantos** [comment]
tem esse post do @suissa também que costumo passar pra galera... 
http://javascriptbrasil.com/2012/10/30/estou-iniciando-em-javascript-por-onde-comeco/

**Comment by andersoonweb** [comment]
Eu estou começando a aprender estou seguindo esses materiais tem esse da [Tuts+](http://code.tutsplus.com/articles/become-a-professional-javascript-developer-with-tuts-courses--cms-21095), são pagos, mas parece que vale a pena.Estava começando ler também a tradução do @randsonjs do livo  Eloquent Javascript, é um livro bem bom mesmo!(Esperando o restante da tradução, pena que não manjo muito de inglês pra puder ajudar).

Recomendo também o artigo que o @ericdouglas ,[traduziu como aprender javascript corretamente](https://github.com/ericdouglas/traduz-ai/blob/master/javascript/001-como-aprender-js-corretamente.md#como-aprender-javascript-corretamente--javascriptis-sexy).
