### ISSUE TITLE
(Idiomatic.js) Princípios para escrever JavaScript de forma Consistente e Idiomática

### ISSUE THREAD

**Issue by henricavalcante** [braziljs/ideias#7]
Segue uma tradução do documento do @rwaldron (https://github.com/rwaldron/idiomatic.js) sobre como escrever um bom JavaScript.

https://github.com/rwaldron/idiomatic.js/tree/master/translations/pt_BR

**Comment by zenorocha** [comment]
Legal @henricavalcante, só não entendi qual a sua ideia?

P.S.: Nós também traduzimos o idiomatic CSS (https://github.com/necolas/idiomatic-css/tree/master/translations/pt-BR).

**Comment by henricavalcante** [comment]
A idéia é que pessoas que forem transferir seus projetos para cá, que seja de forma bem escrita, talvez até esses links devam estar no readme.

**Comment by zenorocha** [comment]
Ah sim, boas práticas são importantes em qualquer cenário, será que você tem como transformar isso num pull request pra ficar mais fácil de visualizar a ideia?
